"""Agregar campo tema a usuarios

Revision ID: 010e974511da
Revises: feb6150a44aa
Create Date: 2026-08-13 16:11:06.732578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '010e974511da'
down_revision = 'feb6150a44aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ruta_parada')
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_secretario', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'usuarios', ['id_secretario'], ['id'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('lineas', schema=None) as batch_op:
        batch_op.drop_column('color')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tema', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('tema')

    with op.batch_alter_table('lineas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=7), server_default=sa.text("'#74A9D3'::character varying"), autoincrement=False, nullable=True))

    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_secretario')

    op.create_table('ruta_parada',
    sa.Column('id_ruta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_parada', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('orden_parada', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_parada'], ['paradas.id'], name=op.f('ruta_parada_id_parada_fkey')),
    sa.ForeignKeyConstraint(['id_ruta'], ['rutas.id'], name=op.f('ruta_parada_id_ruta_fkey')),
    sa.PrimaryKeyConstraint('id_ruta', 'id_parada', name=op.f('ruta_parada_pkey'))
    )
    # ### end Alembic commands ###
