"""Add lineas table

Revision ID: 03c7f2ab7f2d
Revises: c85b35e33522
Create Date: 2026-06-13 21:16:12.379380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c7f2ab7f2d'
down_revision = 'c85b35e33522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('presidente_nombre', sa.String(length=100), nullable=False),
    sa.Column('presidente_cedula', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('rif', sa.String(length=50), nullable=False),
    sa.Column('suspendido', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('secretario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['secretario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineas')
    # ### end Alembic commands ###
