"""Agregar campo color a lineas

Revision ID: 0536821e8f07
Revises: d91a5ad6a68f
Create Date: 2026-07-26 17:35:26.579098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0536821e8f07'
down_revision = 'd91a5ad6a68f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lineas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lineas', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
