"""Agregar nuevos campos:  intentos fallidos y bloqueo temporal

Revision ID: 2de86219e4ce
Revises: 7ef568c8517f
Create Date: 2026-05-17 15:05:12.835777

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2de86219e4ce"
down_revision = "7ef568c8517f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.add_column(sa.Column("intentos_fallidos", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("bloqueado_hasta", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.drop_column("bloqueado_hasta")
        batch_op.drop_column("intentos_fallidos")

    # ### end Alembic commands ###
