"""Add presidente_id to lineas and remove old fields

Revision ID: 372c1b33b80c
Revises: 66a1ba46a352
Create Date: 2026-06-16 17:51:16.884734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372c1b33b80c'
down_revision = '66a1ba46a352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lineas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presidente_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'personas', ['presidente_id'], ['id'])
        batch_op.drop_column('presidente_nombre')
        batch_op.drop_column('telefono')
        batch_op.drop_column('presidente_cedula')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lineas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presidente_cedula', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('presidente_nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('presidente_id')

    # ### end Alembic commands ###
