"""add ubicacion a Bus

Revision ID: 820fa3609e9b
Revises: 3ecba65cfd64
Create Date: 2026-09-26 17:39:58.116659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820fa3609e9b'
down_revision = '3ecba65cfd64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.drop_column('ubicacion')

    # ### end Alembic commands ###
