"""Add rol column to personas

Revision ID: c6981f050bb7
Revises: 372c1b33b80c
Create Date: 2026-06-16 22:19:30.552456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6981f050bb7'
down_revision = '372c1b33b80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lineas', schema=None) as batch_op:
        batch_op.alter_column('presidente_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=20), nullable=True))
        batch_op.alter_column('correo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.alter_column('correo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('rol')

    with op.batch_alter_table('lineas', schema=None) as batch_op:
        batch_op.alter_column('presidente_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
