"""migracion inicial limpia

Revision ID: c71457cbc5b2
Revises: 
Create Date: 2026-07-02 17:20:50.233546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c71457cbc5b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('fecha_nac', sa.Date(), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula')
    )
    op.create_table('lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rif', sa.String(length=50), nullable=False),
    sa.Column('suspendido', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('secretario_id', sa.Integer(), nullable=True),
    sa.Column('presidente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['presidente_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['secretario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('pasos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pasos_timestamp'))

    op.drop_table('pasos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persona_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'personas', ['persona_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('persona_id')

    op.create_table('pasos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bus_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parada_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pasos_pkey'))
    )
    with op.batch_alter_table('pasos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pasos_timestamp'), ['timestamp'], unique=False)

    op.drop_table('lineas')
    op.drop_table('personas')
    # ### end Alembic commands ###
