"""add id_secretario to buses

Revision ID: d4d8a1873daf
Revises: 820fa3609e9b
Create Date: 2026-10-08 22:51:14.559292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d8a1873daf'
down_revision = '820fa3609e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_secretario', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['id_secretario'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_secretario')

    # ### end Alembic commands ###
