"""Inicial

Revision ID: d66363b205bc
Revises: 
Create Date: 2026-04-26 17:00:17.053841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd66363b205bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paradas')
    with op.batch_alter_table('pasos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pasos_timestamp'))

    op.drop_table('pasos')
    op.drop_table('buses')
    op.drop_table('rutas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rutas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rutas_pkey'))
    )
    op.create_table('buses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('ruta_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], name=op.f('buses_ruta_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('buses_pkey')),
    sa.UniqueConstraint('codigo', name=op.f('buses_codigo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('pasos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bus_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parada_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], name=op.f('pasos_bus_id_fkey')),
    sa.ForeignKeyConstraint(['parada_id'], ['paradas.id'], name=op.f('pasos_parada_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pasos_pkey'))
    )
    with op.batch_alter_table('pasos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pasos_timestamp'), ['timestamp'], unique=False)

    op.create_table('paradas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('latitud', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=False),
    sa.Column('longitud', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=False),
    sa.Column('ruta_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], name=op.f('paradas_ruta_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('paradas_pkey'))
    )
    # ### end Alembic commands ###
