"""Agregar campo color a rutas

Revision ID: d91a5ad6a68f
Revises: feb6150a44aa
Create Date: 2026-07-26 17:20:00.238354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91a5ad6a68f'
down_revision = 'feb6150a44aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rutas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rutas', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
