"""Agregar campo color a lineas

Revision ID: dd6aebfe6f64
Revises: 0536821e8f07
Create Date: 2026-07-26 17:57:06.760367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6aebfe6f64'
down_revision = '0536821e8f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rutas', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rutas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=7), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
