"""migracion inicial

Revision ID: f8cf8e5df95c
Revises: 
Create Date: 2026-09-16 16:30:06.606735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8cf8e5df95c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paradas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_ruta', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'rutas', ['id_ruta'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tema', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('tema')

    with op.batch_alter_table('paradas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_ruta')

    # ### end Alembic commands ###
