"""Crear tabla paradas

Revision ID: feb6150a44aa
Revises: c71457cbc5b2
Create Date: 2026-07-09 20:33:19.321191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb6150a44aa'
down_revision = 'c71457cbc5b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paradas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('coordenadas', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lineas', schema=None) as batch_op:
        batch_op.alter_column('presidente_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.alter_column('correo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.alter_column('correo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('lineas', schema=None) as batch_op:
        batch_op.alter_column('presidente_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('paradas')
    # ### end Alembic commands ###
